### ISSUE TITLE
Rapid response problem causing failure in grade report job

### ISSUE THREAD

**Issue by gsidebo** [mitodl/rapid-response-xblock#80] opened 2019-09-18 18:20 UTC
In our instructor dashboard, we allow instructors to request and download a CSV of grades (triggered task: `lms.djangoapps.instructor_task.tasks.calculate_grades_csv`). When an instructor has tried doing this for a course that contains a rapid-response-enabled problem, an exception is raised and the report creation fails.

Two important details:
1. When rapid response is disabled for the given problem, this error goes away
1. We're _pretty_ sure that if the release date for the rapid-response-enabled problem is not in the future, this error goes away

Stack trace:

```
    2019-09-11 10:08:15,185 ERROR 24397 [celery.worker.job] log.py:282 - Task lms.djangoapps.instructor_task.tasks.calculate_grades_csv[de984aea-ceba-404c-bb03-5100b05547a4] raised unexpected: KeyError(BlockUsageLocator(CourseLocator(u'MITx', u'blank.01', u'2019_Fall', None, None), u'sequential', u'a492b76584ff49978a3002e69370423d'),)
    Traceback (most recent call last):
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
        R = retval = fun(*args, **kwargs)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/newrelic/hooks/application_celery.py", line 85, in wrapper
        return wrapped(*args, **kwargs)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
        return self.run(*args, **kwargs)
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks.py", line 187, in calculate_grades_csv
        return run_main_task(entry_id, task_fn, action_name)
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/runner.py", line 111, in run_main_task
        task_progress = task_fcn(entry_id, course_id, task_input, action_name)
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/grades.py", line 211, in generate
        return CourseGradeReport()._generate(context)
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/grades.py", line 223, in _generate
        success_rows, error_rows = self._compile(context, batched_rows)
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/grades.py", line 265, in _compile
        success_rows, error_rows = izip(*batched_rows)
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/grades.py", line 257, in _batched_rows
        yield self._rows_for_users(context, users)
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/grades.py", line 497, in _rows_for_users
        self._user_certificate_info(user, context, course_grade, bulk_context.certs) +
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/grades.py", line 361, in _user_grades
        assignment_info['subsection_headers'],
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/tasks_helper/grades.py", line 379, in _user_subsection_grades
        subsection_grade = course_grade.subsection_grade(subsection_location)
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/grades/course_grade.py", line 58, in subsection_grade
        return self._get_subsection_grade(self.course_data.effective_structure[subsection_key])
      File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 448, in __getitem__
        return self._block_data_map[usage_key]
    KeyError: BlockUsageLocator(CourseLocator(u'MITx', u'blank.01', u'2019_Fall', None, None), u'sequential', u'a492b76584ff49978a3002e69370423d')
```

**Comment by ahmed-arbisoft** [comment] 2019-11-22 11:19
@gsidebo can you please verify if what I'm doing is right?

1. Created a problem unit (rapid response enabled), set the unit to be released in future.
2. Opened course in LMS as staff
3. Went to "Instructor" tab
4. Went to "Data Download" subtab
5. Clicked "Generate Grade Report" button
6. Reports available for download section shows the grade report csv file link after a while

I haven't been able to reproduce this bug, let me know if there is something else I might need to do in order to reproduce it.

**Comment by pdpinch** [comment] 2019-11-22 11:25
The edge case that causes the report to fail is when the rapid response problem has a release date set in the future. See https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/developing_course/course_sections.html#id27 for documentation.

**Comment by ahmed-arbisoft** [comment] 2019-11-22 11:27
@pdpinch this is what I've done in the course I have, notice the scheduled release date for the section:

![Screenshot from 2019-11-22 16-26-23](https://user-images.githubusercontent.com/45350418/69422192-e9d1cf00-0d44-11ea-86df-002e0a6a69fc.png)

**Comment by pdpinch** [comment] 2019-11-22 11:29
That looks right. I'm not sure what else might be necessary. 

Do you have any users enrolled in the course who are not staff (and wouldn't be able to view the problem) ?

**Comment by ahmed-arbisoft** [comment] 2019-11-22 11:30
Yes

**Comment by pdpinch** [comment] 2019-11-22 11:49
Do you have any student state on the problem? 

You might try answering the problem as the instructor, with the rapid response turned on.

**Comment by ahmed-arbisoft** [comment] 2019-11-22 12:00
Ah, I was attempting to answer the problem the traditional way. Just found out how rapid responses are supposed to work properly by "opening the problem". I attempted it as the instructor (also enrolled as a student in the course). Now I see rapid responses available as well in the instructor section.

![Screenshot from 2019-11-22 16-58-56](https://user-images.githubusercontent.com/45350418/69424042-6bc3f700-0d49-11ea-9995-c467b7e1f8c9.png)

However, I'm still unable to break the task. I'll keep digging on this

**Comment by blarghmatey** [comment] 2019-11-26 20:04
So, the crux of the problem is that the block structure returned from the call to `course_data.effective_structure` as managed by the code [here](https://github.com/edx/edx-platform/blob/adb426d56f75f52260ecb41375a5a09f95d562b5/openedx/core/djangoapps/content/block_structure/manager.py#L79) doesn't line up with the list of blocks that are "gradeable" as defined by the logic [here](https://github.com/mitodl/edx-platform/blob/mitx%2Fironwood/lms/djangoapps/grades/context.py#L20).

In the `effective_structure` call there are a number of filters which get applied, including one for whether the block is released as of a given date, whereas the grade context does not appear to incorporate those decisions.

**Comment by pdpinch** [comment] 2019-12-02 15:59
Maybe we just need to cherry pick this commit: https://github.com/edx/edx-platform/commit/5a5c3fd79ec8b7d000eb54180f3b04f573142e24#diff-c0dc4e8dd333ab0f5aa5213b2e2241ad

**Comment by pdpinch** [comment] 2021-11-18 12:44
Looks like this was fixed by https://github.com/mitodl/edx-platform/pull/157

**Closed by pdpinch** 2021-11-18 12:44 UTC
